### ISSUE TITLE
Repo needs description

### ISSUE THREAD

**Issue by thraxil** [appsembler/edx-search#20]
Vanta requires us to have a description set for every repo.

**Comment by OmarIthawi** [comment]
@thraxil I don't have permissions to edit this repo, please add all `@appsembler/openedx` so I can edit it.

**Comment by thraxil** [comment]
Sorry @OmarIthawi. We have 116 repos and I'm often guessing at who the "owner" is to assign these kinds of things to.

**Comment by OmarIthawi** [comment]
@thraxil I'm the defacto owner of this repo! It's just that I don't have the proper GitHub Actions access to change the repo description.

Anyway, here's a good description:

> ElasticSearch indexing and APIs for the edX Platform. This Tahoe fork to supports `has_access` to filter search results.
